<a href="https://colab.research.google.com/github/masha713/numerical-methods/blob/master/%D0%BB%D1%80_4_%D0%94%D0%B5%D0%BC%D0%B5%D1%88%D0%BE%D0%BA_%D0%9C%D0%B0%D1%80%D1%96%D1%8F_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'2.0.2'

In [2]:
matrix = np.random.randint(1, 6, size=(3, 3))

matrix

array([[5, 3, 2],
       [2, 2, 3],
       [2, 3, 3]])

In [3]:
det = np.linalg.det(matrix)
det

np.float64(-10.999999999999996)

In [4]:
product = np.prod(matrix)
product

np.int64(6480)

In [5]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(6480)

In [6]:
sum_1 = np.sum(matrix)
sum_1

np.int64(25)

In [7]:
np.max(matrix)

np.int64(5)

In [8]:
np.min(matrix)

np.int64(2)

In [9]:
np.mean(matrix)

np.float64(2.7777777777777777)

In [10]:
np.sqrt(matrix)

array([[2.23606798, 1.73205081, 1.41421356],
       [1.41421356, 1.41421356, 1.73205081],
       [1.41421356, 1.73205081, 1.73205081]])

In [11]:
row_sums = np.sum(matrix, axis=1).reshape(-1,1)

print("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[10]
 [ 7]
 [ 8]]


In [12]:
vector = np.random.randint(0, 10, size=25)

print("Початковий вектор")
print(vector)

Початковий вектор
[4 0 4 2 3 3 3 4 7 8 4 6 8 6 5 3 2 9 7 3 4 0 3 6 9]


In [13]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 8, 8, 7, 7, 6, 6, 6, 5, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 2,
       2, 0, 0])

In [14]:
a = np.array([[1, -2, 3], [4, 2, -3], [3, -3, 5]])
b = np.array([-5, 0, -9])

x = np.linalg.solve(a, b)
print('Вбудована функція', x.round(1))

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [-1.  2. -0.]
Матричний метод [-1.  2. -0.]


In [15]:
# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(-1.0), np.float64(2.0), np.float64(0.0)]
